import { chromium } from 'playwright-core';
import { spawn } from 'node:child_process';
const out = process.argv[2] ?? '/tmp/claude-0/shots';
const vite = spawn('npx', ['vite', '--port', '5199', '--strictPort'], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 2500));
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 760 } });
page.on('console', (m) => { if (['error', 'warning'].includes(m.type())) console.log('[console]', m.type(), m.text().slice(0, 300)); });
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
await page.goto('http://localhost:5199/#seed=demo&autostart');
await page.waitForFunction(() => window.pd, null, { timeout: 120000 });
await page.evaluate(() => { const { view, engine } = window.pd; engine.setSpeed(0); view.visualPhase = view.rig.lon - 0.5; view.rig.alt = 3200; });
await page.waitForTimeout(2500);
await page.screenshot({ path: `${out}/1-space.png` });
// run to awakening quickly
await page.evaluate(() => { const { world, engine } = window.pd; engine.setSpeed(0); });
const info = await page.evaluate(() => { const { world } = window.pd; let n=0; while(!world.awakened && n<20000){ world.stepPrehistory(40); n+=40;} return { y: world.year, awakened: world.awakened }; });
console.log(info);
await page.evaluate(() => { const { world, engine, view, ui } = window.pd; engine.setSpeed(2); const s = world.activeSettlements()[0]; if (s) { view.flyToCell(s.x, s.y, 450, 0, 0.5); view.visualPhase = (s.x/256*2-1)*Math.PI - 0.4; } });
await page.waitForTimeout(9000);
await page.screenshot({ path: `${out}/2-awakened.png` });
await page.evaluate(() => { const { world, engine, view } = window.pd; engine.setSpeed(4); const s = world.activeSettlements()[0]; if (s) view.flyToCell(s.x, s.y, 9, 0.3, 0.95); view.visualPhase = (s.x/256*2-1)*Math.PI - 0.5; });
await page.waitForTimeout(8000);
await page.screenshot({ path: `${out}/3-close.png` });
await page.evaluate(() => { const { world, ui } = window.pd; const p = world.alive[3]; if (p) ui.select('person', p.id, true); });
await page.waitForTimeout(4000);
await page.screenshot({ path: `${out}/4-person.png` });
await browser.close();
vite.kill();
